// Code generated by ogen, DO NOT EDIT.
package v1specs

type CreateScanRes interface {
	createScanRes()
}

type DeleteScanRes interface {
	deleteScanRes()
}

type GetScanRes interface {
	getScanRes()
}

type ListScansRes interface {
	listScansRes()
}
