// Code generated by ogen, DO NOT EDIT.

package v1specs

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateScanOperation OperationName = "CreateScan"
	DeleteScanOperation OperationName = "DeleteScan"
	GetScanOperation    OperationName = "GetScan"
	ListScansOperation  OperationName = "ListScans"
)
