# URL Scanner Service Configuration
# This is a sample configuration file generated based on the Config struct in internal/config/config.go

# Environment specifies the current running environment (development, production, etc.)
environment: development

# HTTP server configuration
http:
  # Address and port the HTTP server will listen on
  addr: ":8080"
  # Maximum duration for reading the entire request, including the body
  readTimeout: 1m
  # Amount of time allowed to read request headers
  readHeaderTimeout: 10s
  # Maximum duration before timing out writes of the response
  writeTimeout: 2m
  # Maximum amount of time to wait for the next request when keep-alives are enabled
  idleTimeout: 2m
  # Maximum time allowed for processing a single request
  requestTimeout: 10s
  # Maximum number of bytes the server will read parsing the request header
  maxHeaderBytes: 0
  # URL path where metrics are exposed
  metricsPath: /metrics

# Database connection configuration
database:
  # Database authentication credentials
  username: myuser
  password: mypassword
  # Database server connection details
  host: localhost
  port: 5432
  sslMode: disable
  # Name of the database to connect to
  name: scanner
  # Connection pool settings
  maxOpenConnections: 10
  maxIdleConnections: 8
  connMaxLifetime: 3m
  connMaxIdleTime: 3m

# JWT configuration for signing and verifying tokens
jwt:
  # PEM-encoded public key used to verify JWT signatures
  publicKey: ""
  # PEM-encoded private key used to sign JWTs
  privateKey: ""

# Scanner subsystem configuration
scanner:
  # Maximum number of attempts for a single scan job before giving up
  maxAttempts: 5
  # Duration for which scan results are cached and reused
  resultCacheTtl: 1h
  # API key used to authenticate with urlscan.io
  urlscanioApiKey: ""

# Background worker configuration
worker:
  # Maximum duration allowed for a single job execution
  jobTimeout: 1m
  # Number of jobs that can be processed concurrently
  jobConcurrency: 10

# Maximum duration to wait for ongoing requests to complete during shutdown
gracefulShutdownTimeout: 10s
